name: Sync Fork

on

  workflow_dispatch: # Allow manual triggering (optional)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          owner: hpmouton  
          base: main
          head: main 
