name: Sync Fork

on:
  schedule: # Run every 30 minutes (optional)
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual triggering (optional)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: hpmouton  
          base: main
          head: main 
